--1757
select product_id
from Products
where low_fats = 'Y'
and recyclable = 'Y';

--584
SELECT NAME
FROM CUSTOMER
WHERE REFEREE_ID is null or REFEREE_ID != 2;

--595
SELECT name, population, area
FROM WORLD
WHERE AREA >= 3000000
OR POPULATION >= 25000000;

--1148
SELECT DISTINCT AUTHOR_ID ID
FROM VIEWS
WHERE AUTHOR_ID = VIEWER_ID
ORDER BY ID ASC;

--1683
SELECT TWEET_ID
FROM TWEETS
WHERE LENGTH(CONTENT) > 15;

--JOINS

--1378
SELECT UNIQUE_ID, NAME
FROM EMPLOYEES emp
    LEFT JOIN EMPLOYEEUNI uni ON emp.id = uni.id;

--1068
SELECT PRODUCT_NAME, YEAR, PRICE
FROM SALES
    JOIN PRODUCT ON SALES.PRODUCT_ID = PRODUCT.PRODUCT_ID
ORDER BY PRODUCT_NAME ASC;

--577
SELECT NAME, BONUS
FROM EMPLOYEE EMP
LEFT JOIN BONUS BON ON EMP.EMPID = BON.EMPID
WHERE BONUS IS NULL
OR BONUS < 1000;
